services:
  - type: web
    name: sui-task-indexer
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm run start:all
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sui-task-db
          property: connectionString
      - key: PACKAGE_ID
        value: 0x39d1dfff0845ababac9dd640a0dadf9565b0ee6ef6a7de8a488facfc279032de
      - key: NETWORK
        value: testnet
      - key: POLLING_INTERVAL_MS
        value: 1000

databases:
  - name: sui-task-db
    databaseName: sui_task_indexer
    user: sui_task_user
    plan: free
